-- Delete original goody tables
DELETE FROM GoodyHuts;
DELETE FROM HandicapInfo_Goodies;
INSERT INTO GoodyHuts (Type) VALUES ("GOODY_NULL");
INSERT INTO HandicapInfo_Goodies (HandicapType, GoodyType)
VALUES 
("HANDICAP_SETTLER", "GOODY_NULL"), 
("HANDICAP_CHIEFTAIN", "GOODY_NULL"), 
("HANDICAP_WARLORD", "GOODY_NULL"), 
("HANDICAP_PRINCE", "GOODY_NULL"), 
("HANDICAP_KING", "GOODY_NULL"), 
("HANDICAP_EMPEROR", "GOODY_NULL"),
("HANDICAP_IMMORTAL", "GOODY_NULL"),
("HANDICAP_DEITY", "GOODY_NULL");